export const PERMISSIONS = {
  // Scheduling
  GENERATE_SCHEDULE: 'scheduling.generate',
  PUBLISH_SCHEDULE: 'scheduling.publish',
  ROLLBACK_SCHEDULE: 'scheduling.rollback',
  EDIT_CONSTRAINTS: 'scheduling.edit_constraints',
  MODIFY_SOLVER_SETTINGS: 'scheduling.modify_solver',

  // Students
  VIEW_STUDENTS: 'students.view',
  CREATE_STUDENTS: 'students.create',
  EDIT_STUDENTS: 'students.edit',
  DELETE_STUDENTS: 'students.delete',
  IMPORT_STUDENTS: 'students.import',
  EXPORT_STUDENTS: 'students.export',

  // Subjects
  VIEW_SUBJECTS: 'subjects.view',
  CREATE_SUBJECTS: 'subjects.create',
  EDIT_SUBJECTS: 'subjects.edit',
  DELETE_SUBJECTS: 'subjects.delete',
  IMPORT_SUBJECTS: 'subjects.import',
  EXPORT_SUBJECTS: 'subjects.export',

  // Faculty
  VIEW_FACULTY: 'faculty.view',
  MANAGE_DUTIES: 'faculty.manage_duties',
  EDIT_AVAILABILITY: 'faculty.edit_availability',

  // Classrooms
  MANAGE_ROOMS: 'classrooms.manage_rooms',
  EDIT_CAPACITIES: 'classrooms.edit_capacities',

  // Analytics
  VIEW_DASHBOARDS: 'analytics.view_dashboards',
  EXPORT_REPORTS: 'analytics.export_reports',

  // Audit
  VIEW_LOGS: 'audit.view_logs',
  EXPORT_LOGS: 'audit.export_logs',
  VERIFY_INTEGRITY: 'audit.verify_integrity',

  // System
  MANAGE_USERS: 'system.manage_users',
  MANAGE_ROLES: 'system.manage_roles',
  CHANGE_SETTINGS: 'system.change_settings',
  RESTORE_BACKUPS: 'system.restore_backups',
  RUN_MIGRATIONS: 'system.run_migrations',
  ACCESS_DEVELOPER_TOOLS: 'system.access_developer_tools'
};

export const ROLE_PERMISSIONS = {
  'Super Admin': Object.values(PERMISSIONS),
  'Exam Controller': [
    PERMISSIONS.GENERATE_SCHEDULE, PERMISSIONS.PUBLISH_SCHEDULE, PERMISSIONS.ROLLBACK_SCHEDULE,
    PERMISSIONS.EDIT_CONSTRAINTS, PERMISSIONS.MODIFY_SOLVER_SETTINGS,
    PERMISSIONS.VIEW_STUDENTS, PERMISSIONS.CREATE_STUDENTS, PERMISSIONS.EDIT_STUDENTS, PERMISSIONS.DELETE_STUDENTS, PERMISSIONS.IMPORT_STUDENTS, PERMISSIONS.EXPORT_STUDENTS,
    PERMISSIONS.VIEW_SUBJECTS, PERMISSIONS.CREATE_SUBJECTS, PERMISSIONS.EDIT_SUBJECTS, PERMISSIONS.DELETE_SUBJECTS, PERMISSIONS.IMPORT_SUBJECTS, PERMISSIONS.EXPORT_SUBJECTS,
    PERMISSIONS.VIEW_FACULTY, PERMISSIONS.MANAGE_DUTIES,
    PERMISSIONS.MANAGE_ROOMS, PERMISSIONS.EDIT_CAPACITIES,
    PERMISSIONS.VIEW_DASHBOARDS, PERMISSIONS.EXPORT_REPORTS,
    PERMISSIONS.VIEW_LOGS, PERMISSIONS.EXPORT_LOGS,
    PERMISSIONS.CHANGE_SETTINGS
  ],
  'Exam Coordinator': [
    PERMISSIONS.GENERATE_SCHEDULE, PERMISSIONS.EDIT_CONSTRAINTS,
    PERMISSIONS.VIEW_STUDENTS, PERMISSIONS.CREATE_STUDENTS, PERMISSIONS.EDIT_STUDENTS, PERMISSIONS.IMPORT_STUDENTS, PERMISSIONS.EXPORT_STUDENTS,
    PERMISSIONS.VIEW_SUBJECTS, PERMISSIONS.CREATE_SUBJECTS, PERMISSIONS.EDIT_SUBJECTS, PERMISSIONS.IMPORT_SUBJECTS, PERMISSIONS.EXPORT_SUBJECTS,
    PERMISSIONS.VIEW_FACULTY, PERMISSIONS.MANAGE_DUTIES,
    PERMISSIONS.MANAGE_ROOMS, PERMISSIONS.EDIT_CAPACITIES,
    PERMISSIONS.VIEW_DASHBOARDS, PERMISSIONS.EXPORT_REPORTS,
    PERMISSIONS.VIEW_LOGS
  ],
  'Assistant Coordinator': [
    PERMISSIONS.VIEW_STUDENTS, PERMISSIONS.CREATE_STUDENTS, PERMISSIONS.EDIT_STUDENTS,
    PERMISSIONS.VIEW_SUBJECTS, PERMISSIONS.CREATE_SUBJECTS, PERMISSIONS.EDIT_SUBJECTS,
    PERMISSIONS.VIEW_FACULTY, PERMISSIONS.MANAGE_DUTIES,
    PERMISSIONS.VIEW_DASHBOARDS
  ],
  'HOD': [
    PERMISSIONS.VIEW_STUDENTS, PERMISSIONS.VIEW_SUBJECTS, PERMISSIONS.VIEW_FACULTY,
    PERMISSIONS.VIEW_DASHBOARDS, PERMISSIONS.EXPORT_REPORTS
  ],
  'Faculty': [
    PERMISSIONS.VIEW_STUDENTS, PERMISSIONS.VIEW_SUBJECTS, PERMISSIONS.VIEW_FACULTY,
    PERMISSIONS.EDIT_AVAILABILITY
  ],
  'Invigilator': [
    PERMISSIONS.VIEW_SUBJECTS, PERMISSIONS.EDIT_AVAILABILITY
  ],
  'Kiosk': [
    PERMISSIONS.VIEW_STUDENTS, PERMISSIONS.VIEW_SUBJECTS
  ],
  'Auditor': [
    PERMISSIONS.VIEW_STUDENTS, PERMISSIONS.VIEW_SUBJECTS, PERMISSIONS.VIEW_FACULTY,
    PERMISSIONS.VIEW_LOGS, PERMISSIONS.EXPORT_LOGS, PERMISSIONS.VERIFY_INTEGRITY
  ],
  'Read Only': [
    PERMISSIONS.VIEW_STUDENTS, PERMISSIONS.VIEW_SUBJECTS, PERMISSIONS.VIEW_FACULTY,
    PERMISSIONS.VIEW_DASHBOARDS
  ]
};

// Fallback helper to map old single DB roles to modern IAM roles
export function mapLegacyRole(legacyRole) {
  if (legacyRole === 'coordinator') return ['Exam Coordinator'];
  if (legacyRole === 'faculty') return ['Faculty'];
  return [legacyRole];
}
